[package]
name = "lib4bottle"
version = "0.1.0"
authors = [ "Robey Pointer <robeypointer@gmail.com>" ]

[dependencies]
lazy_static = "0.2.4"
futures = "0.1"
bytes = "0.4"

[profile.test]
opt-level = 3
